# Generated by Django 6.0.5 on 2026-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_force', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_attachments/'),
        ),
    ]
